version: '3'

services:
  web:
    build: .
    command: ruby bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    links:
      - postgres
    ports:
      - "3000:3000"
    expose:
      - "3000"

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ".:/app"
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres:
